AWSTemplateFormatVersion: '2010-09-09'
Description: Stack for compute resources that run displomacy bot.

Resources:
  CodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'displomacy-code-com'