AWSTemplateFormatVersion: '2010-09-09'
Description: Stack for compute resources that run the bot.

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'displomacy-players'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: S
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      Tags:
        - Key: project
          Value: displomacy 

  GameTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'displomacy-games'
      AttributeDefinitions:
        - AttributeName: 'channel'
          AttributeType: S
      KeySchema:
        - AttributeName: 'channel'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      Tags:
        - Key: project
          Value: displomacy 
  
  OrderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'displomacy-orders'
      AttributeDefinitions:
        - AttributeName: 'channel'
          AttributeType: S
        - AttributeName: 'player'
          AttributeType: S
      KeySchema:
        - AttributeName: 'channel'
          KeyType: 'HASH'
        - AttributeName: 'player'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      Tags:
        - Key: project
          Value: displomacy
  
  TurnHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'displomacy-turn-history'
      AttributeDefinitions:
        - AttributeName: 'channel'
          AttributeType: S
        - AttributeName: 'turn'
          AttributeType: S
      KeySchema:
        - AttributeName: 'channel'
          KeyType: 'HASH'
        - AttributeName: 'turn'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      Tags:
        - Key: project
          Value: displomacy
  
  GameHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'displomacy-game-history'
      AttributeDefinitions:
        - AttributeName: 'channel'
          AttributeType: S
        - AttributeName: 'id'
          AttributeType: S
      KeySchema:
        - AttributeName: 'channel'
          KeyType: 'HASH'
        - AttributeName: 'id'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      Tags:
        - Key: project
          Value: displomacy

  StateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'displomacy-states-com'